//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbsurdEntities : DbContext
    {
        public AbsurdEntities()
            : base("name=AbsurdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ETA_Comment> ETA_Comment { get; set; }
        public virtual DbSet<ETA_Error> ETA_Error { get; set; }
        public virtual DbSet<ETA_FactionPost> ETA_FactionPost { get; set; }
        public virtual DbSet<ETA_Blog> ETA_Blog { get; set; }
        public virtual DbSet<ETA_FactionThread> ETA_FactionThread { get; set; }
        public virtual DbSet<ETA_User> ETA_User { get; set; }
        public virtual DbSet<ETA_BlogStorage> ETA_BlogStorage { get; set; }
        public virtual DbSet<ETA_CrossWord> ETA_CrossWord { get; set; }
        public virtual DbSet<ETA_Post> ETA_Post { get; set; }
        public virtual DbSet<ETA_Puzzles> ETA_Puzzles { get; set; }
        public virtual DbSet<ETA_Thread> ETA_Thread { get; set; }
    }
}
