//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_BlogStorage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string TitleImage { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Author { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> Edits { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public int Views { get; set; }
        public int Comments { get; set; }
        public string KarmaVoters { get; set; }
        public int KarmaUp { get; set; }
        public int KarmaDown { get; set; }
        public int KarmaTotal { get; set; }
        public string KarmaPercent { get; set; }
        public string KarmaVotes { get; set; }
        public string Subject { get; set; }
        public string Category { get; set; }
    }
}
