//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_CrossWord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GridX { get; set; }
        public int GridY { get; set; }
        public int GridTotal { get; set; }
        public int Questions { get; set; }
        public string Clues { get; set; }
        public string Positions { get; set; }
        public string Answers { get; set; }
        public string Directions { get; set; }
        public string Author { get; set; }
        public System.DateTime Date { get; set; }
        public string Completed { get; set; }
    }
}
