//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_Comment
    {
        public int Id { get; set; }
        public Nullable<bool> Blog { get; set; }
        public Nullable<bool> Game { get; set; }
        public Nullable<bool> Thread { get; set; }
        public Nullable<bool> Post { get; set; }
        public Nullable<bool> Puzzle { get; set; }
        public string Author { get; set; }
        public string Body { get; set; }
        public System.DateTime Date { get; set; }
        public int Votes { get; set; }
        public int Upvotes { get; set; }
        public int DownVotes { get; set; }
        public int ParentId { get; set; }
    }
}
