//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_Post
    {
        public int Id { get; set; }
        public int ThreadId { get; set; }
        public string Body { get; set; }
        public string Quote { get; set; }
        public string Author { get; set; }
        public string AuthorAvatar { get; set; }
        public int Votes { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
        public string Voters { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
        public string Edit { get; set; }
        public Nullable<int> EditAmounts { get; set; }
        public Nullable<int> Comments { get; set; }
        public string Image { get; set; }
    }
}
