//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_Error
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Error { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Resolved { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
    }
}
