//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_Puzzles
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Author { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> EditAmount { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public Nullable<int> Comments { get; set; }
        public int Votes { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
        public string Voters { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public string Difficulty { get; set; }
        public string Completed { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Answer { get; set; }
    }
}
