//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETAbsurdV1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETA_User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string Password { get; set; }
        public decimal Reputation { get; set; }
        public Nullable<int> ReputationAverage { get; set; }
        public string ReputationVotes { get; set; }
        public string ReputationVoteDates { get; set; }
        public string RepTag { get; set; }
        public string RepTagHistory { get; set; }
        public int Posts { get; set; }
        public int Threads { get; set; }
        public string Avatar { get; set; }
        public string TextColor { get; set; }
        public string Signature { get; set; }
        public string Font { get; set; }
        public int UpVotes { get; set; }
        public int DownVotes { get; set; }
        public int CompetitionEntries { get; set; }
        public string CompetitionsEntered { get; set; }
        public int CompetitionsWon { get; set; }
        public int CompetitionsSecond { get; set; }
        public int CompetitionsThird { get; set; }
        public int CompetitionsTopTen { get; set; }
        public string Medals { get; set; }
        public string HasVoted { get; set; }
        public int GivenUpVotes { get; set; }
        public int GivenDownVotes { get; set; }
        public string GivenVoteDates { get; set; }
        public string PasswordRetrievalCode { get; set; }
        public bool Blogger { get; set; }
        public int Blogs { get; set; }
        public Nullable<int> BlogFrequency { get; set; }
        public string Following { get; set; }
        public int KarmaUp { get; set; }
        public int KarmaDown { get; set; }
        public Nullable<int> KarmaTotal { get; set; }
        public Nullable<System.DateTime> RecentBlog { get; set; }
        public Nullable<System.DateTime> RecentThread { get; set; }
        public string RecentPost { get; set; }
        public string Faction { get; set; }
        public int FactionPosts { get; set; }
        public Nullable<int> FactionContribution { get; set; }
        public int FactionUpVotes { get; set; }
        public int FactionDownVotes { get; set; }
    }
}
